name: drQuests
version: '1.1'
main: uwu.nekorise.drQuests.DrQuests
api-version: '1.21'
authors: [ Nekorise ]
commands:
  quests: {}

# TODO:
# exploring & running quests listener
# quest rewards (items+command)
# in-plugin placeholders
# PAPI
# main config
# strings (lang cfgs)
